# Generated by Django 4.0.3 on 2022-03-31 08:56

import app.rules.enums
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('d8448e42-db39-4402-99b7-64d46d0ae20d'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=64)),
                ('comment', models.TextField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Ruleset',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('218da964-d7b8-47a6-ab19-ddc7ec281026'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=64)),
                ('comment', models.TextField(blank=True, max_length=255)),
                ('source', models.TextField(max_length=255)),
                ('destination', models.TextField(max_length=255)),
                ('service', models.TextField(max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'INBOUND'), ('OUTBOUND', 'OUTBOUND')], default=app.rules.enums.Direction['INBOUND'], max_length=64)),
                ('action', models.TextField(choices=[('ACCEPT', 'ACCEPT'), ('DENY', 'DENY')], default=app.rules.enums.Action['ACCEPT'], max_length=64)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleset', to='rules.ruleset')),
            ],
            options={
                'verbose_name': 'Rule',
            },
        ),
    ]
