# Generated by Django 4.0.3 on 2022-03-30 12:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('81d5a633-1346-4b09-a71e-5d3f5b4f26a8'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=64)),
                ('comment', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'Ruleset',
            },
        ),
    ]
