# Generated by Django 4.0.3 on 2022-03-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules_old', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleSet',
        ),
    ]
