# Generated by Django 4.0.3 on 2022-04-04 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.UUID('b9b51914-cb9d-409a-abe9-6a829f480d9c'), primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=255)),
                ('defs', models.JSONField()),
            ],
            options={
                'verbose_name': 'Object',
            },
        ),
    ]
