# Generated by Django 4.0.3 on 2022-03-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=255)),
                ('defs', models.JSONField()),
            ],
            options={
                'verbose_name': 'Object',
            },
        ),
    ]
