# Generated by Django 4.0.3 on 2022-04-04 06:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a603c91e-b93d-4443-aef6-0f4477a17467'), primary_key=True, serialize=False),
        ),
    ]
