# Generated by Django 4.0.3 on 2022-03-30 12:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('7ae34bc6-1940-4df3-86ca-e6b9fce71bf0'), primary_key=True, serialize=False),
        ),
    ]
