# Generated by Django 4.0.3 on 2022-03-31 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('8b96fcc4-84a0-4f9b-a742-a2a3b2810091'), primary_key=True, serialize=False),
        ),
    ]
