# Generated by Django 4.0.3 on 2022-03-31 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('bb274ae0-9aec-415b-bf38-9f12964f2f03'), primary_key=True, serialize=False),
        ),
    ]
