# Generated by Django 4.0.3 on 2022-03-31 10:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('d44eeec8-5090-4742-bc88-224386a2c8db'), primary_key=True, serialize=False),
        ),
    ]
