# Generated by Django 4.0.3 on 2022-04-01 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('bdc9d016-01c2-4036-8aee-b0a306407119'), primary_key=True, serialize=False),
        ),
    ]
