# Generated by Django 4.0.3 on 2022-04-03 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0006_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('a9bc50a6-febc-4483-9772-fbd1329a6add'), primary_key=True, serialize=False),
        ),
    ]
