# Generated by Django 4.0.3 on 2022-04-03 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0007_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('1e053447-82d6-4ea4-9214-74a16cbd4d6e'), primary_key=True, serialize=False),
        ),
    ]
