# Generated by Django 4.0.3 on 2022-04-03 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0008_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('91c04ca6-ab41-4530-905e-bb83f16773e7'), primary_key=True, serialize=False),
        ),
    ]
