# Generated by Django 4.0.3 on 2022-04-03 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0009_alter_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('23422cb1-d96d-438d-8eb7-56bd51a451d5'), primary_key=True, serialize=False),
        ),
    ]
