# Generated by Django 4.0.3 on 2022-04-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='source',
        ),
        migrations.AddField(
            model_name='rule',
            name='destinations',
            field=models.ManyToManyField(related_name='rule_destinations', to='api.object'),
        ),
        migrations.AddField(
            model_name='rule',
            name='sources',
            field=models.ManyToManyField(related_name='rule_sources', to='api.object'),
        ),
    ]
