# Generated by Django 4.0.3 on 2022-05-07 17:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icmp_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='icmp_type',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='api.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='port_end',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='port_start',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='protocol',
            field=models.CharField(blank=True, choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP')], max_length=64, null=True),
        ),
    ]
