# Generated by Django 4.0.3 on 2022-04-04 12:07

import app.api.enums
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=64)),
                ('comment', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('FIREWALL', 'FIREWALL'), ('CLUSTER', 'CLUSTER')], default=app.api.enums.DeviceType['FIREWALL'], max_length=64)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.repository')),
            ],
            options={
                'verbose_name': 'Device',
            },
        ),
    ]
