# Generated by Django 4.0.3 on 2022-05-05 12:28

import app.api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lock',
            field=models.CharField(blank=True, choices=[('LOCKED', app.api.enums.LockStatus['LOCKED']), ('UNLOCKED', app.api.enums.LockStatus['UNLOCKED'])], default=app.api.enums.LockStatus['UNLOCKED'], max_length=64),
        ),
    ]
