# Generated by Django 4.0.3 on 2022-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_service_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='members',
            field=models.ManyToManyField(blank=True, to='api.service'),
        ),
    ]
