# Generated by Django 4.0.3 on 2022-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_service_lock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionservice',
            name='members',
        ),
        migrations.AddField(
            model_name='collectionservice',
            name='services',
            field=models.ManyToManyField(related_name='collection_services', to='api.service'),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
