# Generated by Django 4.0.3 on 2022-04-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rule_destination_remove_rule_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='service',
        ),
        migrations.AddField(
            model_name='rule',
            name='services',
            field=models.ManyToManyField(related_name='rule_services', to='api.service'),
        ),
    ]
