# Generated by Django 4.0.3 on 2022-04-29 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_rule_service_rule_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={},
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='rule',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_folders', to='api.folder'),
        ),
        migrations.AlterField(
            model_name='device',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.repository'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.repository'),
        ),
        migrations.AlterField(
            model_name='object',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectlist', to='api.repository'),
        ),
        migrations.AlterField(
            model_name='rule',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.device'),
        ),
        migrations.AlterField(
            model_name='service',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.repository'),
        ),
    ]
