# Generated by Django 4.0.3 on 2022-05-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_service_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='ipv6_range_end',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='ipv6_range_start',
            field=models.TextField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='object',
            name='members',
            field=models.ManyToManyField(blank=True, to='api.object'),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.CharField(choices=[('IPV4', 'IPV4'), ('IPV6', 'IPV6'), ('COLLECTION', 'COLLECTION')], default='IPV4', max_length=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.TextField(max_length=128),
        ),
        migrations.AlterField(
            model_name='object',
            name='range_end',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='object',
            name='range_start',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
