# Generated by Django 4.0.3 on 2022-04-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_object_service_ruleset_rule_folder_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='comment',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rule',
            name='name',
            field=models.TextField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
