# Generated by Django 4.0.3 on 2022-04-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rule_comment_rule_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='folder',
        ),
        migrations.AddField(
            model_name='rule',
            name='device',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='device_rules', to='api.device'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='ruleset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruleset_rules', to='api.ruleset'),
        ),
    ]
