# Generated by Django 4.0.3 on 2022-04-29 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_folder_options_remove_folder_parent_folder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFolder',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='api.device')),
            ],
            options={
                'verbose_name': 'Device Folder',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rule_folders', to='api.devicefolder'),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
