# Generated by Django 4.0.3 on 2022-05-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_object_ipv6_range_end_object_ipv6_range_start_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('id', 'repository')},
        ),
    ]
