# Generated by Django 4.0.3 on 2022-04-29 13:50

import app.api.enums
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devicefolder_alter_rule_folder_delete_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='lock',
            field=models.CharField(choices=[app.api.enums.LockStatus['LOCKED'], app.api.enums.LockStatus['UNLOCKED']], default=app.api.enums.LockStatus['UNLOCKED'], max_length=64),
        ),
        migrations.AddField(
            model_name='service',
            name='lock',
            field=models.CharField(choices=[app.api.enums.LockStatus['LOCKED'], app.api.enums.LockStatus['UNLOCKED']], default=app.api.enums.LockStatus['UNLOCKED'], max_length=64),
        ),
        migrations.AlterField(
            model_name='rule',
            name='folder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rule_folders', to='api.devicefolder'),
            preserve_default=False,
        ),
    ]
