# Generated by Django 4.0.3 on 2022-04-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_collection_folder_rule_device_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='device',
        ),
    ]
