# Generated by Django 4.0.3 on 2022-05-02 05:26

import app.api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_object_lock_service_lock_alter_rule_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='services',
        ),
        migrations.AddField(
            model_name='rule',
            name='services_destinations',
            field=models.ManyToManyField(blank=True, null=True, related_name='rule_services_destination', to='api.service'),
        ),
        migrations.AddField(
            model_name='rule',
            name='services_sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='rule_services_source', to='api.service'),
        ),
        migrations.AlterField(
            model_name='object',
            name='lock',
            field=models.CharField(choices=[('LOCKED', app.api.enums.LockStatus['LOCKED']), ('UNLOCKED', app.api.enums.LockStatus['UNLOCKED'])], default=app.api.enums.LockStatus['UNLOCKED'], max_length=64),
        ),
        migrations.AlterField(
            model_name='service',
            name='lock',
            field=models.CharField(choices=[('LOCKED', app.api.enums.LockStatus['LOCKED']), ('UNLOCKED', app.api.enums.LockStatus['UNLOCKED'])], default=app.api.enums.LockStatus['UNLOCKED'], max_length=64),
        ),
    ]
