# Generated by Django 4.0.3 on 2022-04-04 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='port',
            new_name='port_end',
        ),
        migrations.AddField(
            model_name='service',
            name='port_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)]),
            preserve_default=False,
        ),
    ]
